### ISSUE TITLE
Jaki sposób komunikacji?

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#1]
1. Co do githuba, to ten wpis będzie stanowił przykład, jak może wyglądać taka rozmowa.
2. Komentarze w treści już częściowo są, staram się uzupełniać kolejne etapy.
3. Mail też może być, jednak chodzi o to, żeby w miarę możliwości nie latać po piętnastu miejscach, aby sprawdzić, czy ktoś coś napisał. Po prostu chciałbym wiedzieć, która droga komunikacji będzie "tą główną".
4. Jeśli jesteś zmęczony, to może odpuścimy sobie na razie IRCa. Chyba, że zajdzie potrzeba omówienia czegoś w czasie rzeczywistym, ale wydaje mi się, że lepiej na razie skupić się na samej treści, a ewentualne pytania gromadzić w jednym miejscu.

**Comment by nalesnik127** [comment]
Spoko, może być tutaj, masz rację z tym szukaniem po plikach odpowiedzi.
