### ISSUE TITLE
Analiza kosztów

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#11]
> RK: Czy obliczanie kosztu na podstawie liczby godzin spędzonych nad projektem to dobry pomysł? Dorzucamy jakieś koszty dodatkowe?
AO: Myślę, że tak, co prawda nie wiem ile brać za godzinę, ale to raczej mały problem.
Koszty dodatkowe, to np. stacja robocza (z wyposażeniem) pod system w każdym gabinecie, może też nauka pracowników?

Chyba lepiej nie mieszać nic ze stawką za godzinę, tylko po prostu podać cenę. Tak będzie nieco bezpieczniej, a spodziewam się, że pewnie chodzi głównie o cenę końcową, natomiast ceny pośrednie są chyba po to, aby zorientować się, na ile bogatą ofertę szykujemy. Z tą implementacją (i wdrożeniem?) to też się zastanawiam, może jeszcze dorzucimy koszt przeróbki strony internetowej? W koszty wkładamy tylko to, za co sami dostaniemy zapłatę, czy liczymy również koszty pośredników, którzy zrobią coś za nas? Czyli na przykład zewnętrzna firma, która, nie wiem, wykona jakiśtam remont?

**Comment by nalesnik127** [comment]
Sam wspomniałeś o obliczaniu kosztu na podstawie liczby godzin. Do tego, chyba musimy mieć hipotetyczną stawkę godzinową?
Pewnie przerobienie strony internetowej też się wpisuje( i cała reszta, z: "Wymagania niefunkcjonalne"), to ma być całkowity koszt wszystkiego, łącznie z pensją podwykonawców

**Comment by robertkopec5** [comment]
Wprowadziłem koszty, mam nadzieję, że mają jakikolwiek sens. W razie czego otwórz.
