### ISSUE TITLE
Numer domów wolnostojących

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#12]
Zero czy NULL? Niby drobiazg, ale nie jestem pewny, jak jest poprawnie. Tak samo, jak pusty ciąg znaków nie jest tym samym, co brak jakiegokolwiek napisu. A jeśli to zero, to chyba trzeba dać regułę mówiącą o tym, że jeśli numer domu wynosi zero, to go nie wyświetlamy (bo będzie to głupio wyglądało na wydrukowanym formularzu, czasami w niektórych programach widziałem z kolei wartości -1, które miały coś wyłączyć, ale były podawane użytkownikom, co było dość dziwne).

**Comment by nalesnik127** [comment]
Może być w sumie pusty ciąg znaków, też będzie git. Jeśli uważasz, że powinna się pojawić jakaś reguła to ją wpisz, jeśli będą jakieś kłopotliwe, to się do nich wróci

**Comment by robertkopec5** [comment]
A przy NULLach chyba nie trzeba pisać takich dodatkowych reguł. A może po prostu połączyć numer domu z numerem mieszkania? W sumie to dlaczego to jest rozdzielone? Nie wiem, będziemy coś wyszukiwać? Mamy mnóstwo klientów z jednego bloku? Poza tym, jeśli to jest małe miasteczko, a obok mamy sporo klientów mieszkających na wsi lub w domach wolnostojących, to takich zer lub NULLi będzie sporo, a mamy ich unikać.

**Comment by robertkopec5** [comment]
Połączyłem numer domu z numerem mieszkania. W ten sposób całość wstawiamy jako tekst (bo w środku jest ukośnik), a nie jako liczbę (nie będziemy tych numerów porównywać ani tym bardziej na przykład dodawać). Dzięki temu będzie mniej NULLi, a przypadki, gdzie ten numer będzie dwuczęściowy uznaję jako dość rzadkie ze względu na zakres (małe miasteczko). Zamykam.
