### ISSUE TITLE
Podpunkty i pogrubienia w 2.1

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#3]
Czasami przeglądam całość od zera, aby odświeżyć sobie obraz całości. Czy w tym całym opisie pogrubić wszystkie słowa kluczowe, czy zostawić tak, jak jest? Bo obecnie chyba zostały poprzednie pogrubienia i później raczej nikt już tego nie ruszał.

**Comment by nalesnik127** [comment]
Myślę, że słowa kluczowe powinny być pogrubione tylko przy pierwszym wystąpieniu, żeby tekst był czytelny, jeśli jakieś nie są, to pewnie, nie wahaj się ich zmienić.

**Comment by robertkopec5** [comment]
Same pogrubienia można przejrzeć, ale to tylko efekt wizualny. Zastanawiam się bardziej nad przeredagowaniem tej analizy tak, aby te podpunkty były nieco bogatsze. Z jednej strony nie chcę psuć za bardzo tego głównego tekstu, który jest dość dobrze napisany (bjutiful mogło zostać, ale mniejsza z tym), a z drugiej strony same podpunkty są dość krótkie i nie wiem, czy to rzeczywiście wystarczy.

**Comment by robertkopec5** [comment]
A może całkiem wywalić pogrubienia z tego głównego tekstu analizy? Może nawet tak będzie lepiej, a powód analogiczny do zaczynania takich wyrazów z wielkiej litery - po prostu niepotrzebne zwracanie uwagi na co drugie, trzecie słowo (w niektórych miejscach, ale jak wywalać, to raczej z całości, żeby było jednolicie).

**Comment by robertkopec5** [comment]
Wywaliłem pogrubienia. Zamykam.
