### ISSUE TITLE
Coś jeszcze w 2.5?

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#4]
Wpisałem o tym drukowaniu, bo to się może przydać. Zostawiamy tak, jak jest, czy próbujemy do tego coś jeszcze dorzucić? Nie wiem, jakaś obsługa niepełnosprawnych czy coś takiego (a może zakładamy, że obecna strona internetowa obsługuje na przykład "duży kontrast" lub inne takie dodatki?). Zresztą, czy będziemy ruszać cokolwiek w samej istniejącej stronie internetowej? Bo jak będą jakieś konta, logowanie i tak dalej, to jednak tego jest trochę więcej, niż przeglądanie w pierwotnej wersji dla gościa.

**Comment by nalesnik127** [comment]
Tak masz rację, strona internetowa musi się trochę zmienić. "Duży kontrast" i inne dodatki mogą się przydać. Coś bym tam jeszcze dopisał, bo punkt wydaje się dość ubogi, można napisać o potrzebie zakupu pecetów, przearanżowaniu strony przez zewnętrznego kontrahenta, czy nauce obsługi systemu przez pracowników

**Comment by nalesnik127** [comment]
Dopisałem część, "duży kontrast lub inne takie dodatki" zostawiam Tobie, bo chyba wiesz lepiej ode mnie o co chodzi

**Comment by robertkopec5** [comment]
Dobra, starczy tyle, co jest. Biorę się za następne etapy.
