### ISSUE TITLE
Użytkownik - poziom dostępu

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#7]
> AO: rola użytkownika, np. Pacjent
RK: z tego wynika, że wszystkich użytkowników trzymamy w jednej tabeli.
AO: W takim razie trzeba to chyba zrealizować inaczej.

Inaczej, czyli jak? Każda rola w osobnej tabeli? Dobrze, w takim razie do czego w ogóle ma służyć to pole? Wszyscy po tym dziedziczą, czyli na liście pacjentów każdy pacjent będzie miał wpisaną rolę "Pacjent". Do czego to jest potrzebne? Zakładam, że chciałeś jakoś pokazać to dziedziczenie, ale dołożenie nowego pola do użytkownika raczej tego nie załatwi. Może w dalszych etapach się to wpisuje? Nie wiem, jeszcze poszukam co nieco o dziedziczeniu.

**Comment by nalesnik127** [comment]
Nie wiem. Jak myślisz, że byłoby najlepiej? 
To prawda, chciałem pokazać dziedziczenie i jakoś to połączyć.

**Comment by robertkopec5** [comment]
Tutaj mamy same pola, czyli po prostu musimy to stamtąd wywalić. Tak samo, jak piszesz w C++, Javie, czy czymśtam innym: dołożenie informacji o klasie pochodnej w klasie podstawowej to coś w stylu ręcznego implementowania polimorfizmu. Czyli można to dodać najwyżej w klasach pochodnych, jednak to z kolei byłaby kompozycja (która udawałaby dziedziczenie). Nie, moim zdaniem w ogóle taką informację trzeba wsunąć gdzieś indziej (dalsze etapy? nie wiem, być może). Jak nie znajdziemy sensownego miejsca, to zapiszemy to słownie, ale kojarzy mi się, że jakiś etap to uwzględniał.

**Comment by robertkopec5** [comment]
1. Wywalam poziom dostępu - użytkownik tego nie potrzebuje. Zresztą zakładam, że użytkownik jako taki nie istnieje, a to, co tutaj jest, to ma się powtórzyć we wszystkich pozostałych rolach.
2. Użytkownik nie dostaje IdU, ponieważ inne role mają swoje tabele i swoje IdP, IdL, IdR i tak dalej.
