### ISSUE TITLE
Specjalizacja lekarza

### ISSUE THREAD

**Issue by robertkopec5** [klinika-baza/klinika-baza#9]
> AO: TO CHYBA POWINNIEN BYĆ ATRYBUT Z OSOBNEJ TABELI – ‘Specjalizacje’
RK: Jakie mamy specjalizacje?

Wszystko zależy od tego, co z tymi specjalizacjami robimy i czy się powtarzają. Jeśli same specjalizacje po prostu trzymamy w bazie (podobnie, jak adresy użytkowników) i traktujemy to jak dane, które chcemy mieć, ale bez żadnego szerszego przetwarzania, to wtedy zwykły tekst wystarczy. Jeśli natomiast nasz pacjent może sobie wyszukać lekarza z daną specjalizacją albo jeśli same specjalizacje się bardzo często powtarzają, to wtedy oczywiście osobna tabela.

**Comment by nalesnik127** [comment]
Sugerowałem się czymś takim jak na laboratorium - tabela: Miasta. W kategoriach nie może być atrybutów z innych kategorii - stąd notatka. Koniec końców, w gruncie rzeczy, chodziło mi o to, żeby wypełnić do maksa kategorie atrybutami, bo wydawały mi się jakieś gołe

**Comment by robertkopec5** [comment]
> W kategoriach nie może być atrybutów z innych kategorii
Ale nie mamy kategorii "Specjalizacja". Dodajemy ją?

**Comment by nalesnik127** [comment]
Na razie bym to pominął, to był zwykły wypełniacz miejsca. Jak się dobrze zastanowiłem, to nawet nie wiem jakie specjalizacje by wpisywać, byłyby pewnie ze dwie, trzy. Z drugiej strony jakoś trzeba przydzielać zabiegi do lekarzy, więc może w Zabiegu jakoś to pokazać?

**Comment by robertkopec5** [comment]
Skoro to był zwykły wypełniacz, to będzie zwykłym kawałkiem tekstu.
